server:
  servlet:
    context-path: /
  port:
    8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 300s
      routes:
        - id: story-service
          uri: lb://story-service
          predicates:
            - Path=/api/story-service/** , /api/story-service/v3/api-docs

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/story-service/v3/api-docs
        name: Story Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost